version: '3'

services:
  mongo:
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - "${MONGO_VOLUME}:/data/db"